version: "3.4"
services:
  bsc-node.ryandunn.eth:
    image: "bsc-node.ryandunn.eth"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.0.0
    volumes:
      - "geth:/data/bsc"
    environment:
      - "EXTRA_OPTS= --syncmode full --gcmode archive --txlookuplimit 0 --http.api admin,debug,web3,eth,txpool,personal,parlia,miner,net --http.corsdomain '*' --ws --ws.api admin,debug,web3,eth,txpool,personal,parlia,miner,net --ws.origins '*' --graphql --graphql.corsdomain '*'"
      - "SYNCMODE= full"
    ports:
      - "30311"
      - 30311/udp # NODE P2P
      - 30311/tcp # NODE P2P
      - 6060/tcp  # pprof / metrics
      - 8545/tcp  # HTTP based JSON RPC API
      - 8546/tcp  # WebSocket based JSON RPC API
    restart: always
volumes:
  geth: {}