version: "3.4"
services:
  #binance-smart-chain.dnp.dappnode.eth:
  '0xf18686AcB3bfE4353f3aBd7Edad784Dc3D31E69f'
    image: "binance-smart-chain.ryandunn.eth:1.0.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.0.0
    volumes:
      - "geth:/root/.ethereum"
    environment:
      - "EXTRA_OPTS=--http.api eth,net,web3,txpool --nousb"
      - SYNCMODE
    ports:
      - "30311"
      - 30311/udp # NODE P2P
      - 30311/tcp # NODE P2P
      - 6060/tcp  # pprof / metrics
      - 8545/tcp  # HTTP based JSON RPC API
      - 8546/tcp  # WebSocket based JSON RPC API
    restart: always
volumes:
  geth: {}
